import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import AdminLayout from "@/components/layouts/AdminLayout";
import { Space, Title } from "@mantine/core";
import CalenderWidget from "@/components/dashboard-components/widgets/CalenderWidget";
import BookingWidget from "@/components/dashboard-components/widgets/BookingWidget";
import NeedHelpWidget from "@/components/dashboard-components/widgets/NeedHelpWidget";
import SetTakeWayWidget from "@/components/dashboard-components/widgets/SetTakeWayWidget";
import UpdateProducts from "@/components/dashboard-components/widgets/UpdateProducts";
import GuideWidget from "@/components/dashboard-components/widgets/GuideWidget";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout title="RESOX">
        <Space h={"xl"} />
        <CalenderWidget />
        <BookingWidget />
        <NeedHelpWidget />
        <SetTakeWayWidget />
        <UpdateProducts />
        <GuideWidget />
      </AdminLayout>
    </>
  );
}
